= Практическая работа 1

Первая практическая работа посвящена проверке Ваших навыков работе в Linux.

Мы полагаем, что Вы уже выполнили требования и задания xref:lab1.adoc[Лабораторной работы 1].

В процессе выполнения *обязательно* документируйте используемые команды (или конкретные действия, например при редактировании файлов) — это часть отчётности.

== Базовая часть

> Стоимость — 2 балла

С аккуратным понятийным аппаратом о графах Вы познакомитесь на дискретной математике.
Грубо говоря, граф — набор вершин и рёбер, связывающих вершины.
С помощью графов моделируют социальные сети, транспортные маршруты, компьютерные сети и многие другие структуры.
Поскольку реальные графы могут иметь миллионы вершин, возникает задача раскладки графа.
Одним из инструментов, решающих данную задачу является link:https://graphviz.org/[graphviz].

В базовой части Вам необходимо выполнить следующие действия, стараясь максимально использовать командную оболочку и утилиты:

1. Установить graphviz.
2. Скачать из галерии примеров (есть на сайте) понравившийся.
    - Если сайт graphviz недоступен, можно поискать примеры (ищите файлы с расширениями `.gv.txt` или `.gv`) здесь:
        - https://gitlab.com/graphviz/graphviz.gitlab.io/-/tree/main/content/en/Gallery?ref_type=heads
        - https://gitlab.com/graphviz/graphviz/-/tree/main/graphs/directed?ref_type=heads
3. Сконвертировать текстовое представление графа в изображение.
4. Отредактировать пример, добавив туда вершину, содержащую Ваше имя, фамилию и группу.
5. Сконвертировать измененный граф в изображение с другим именем.

В качестве отчёта: сдать на HwProj список действий и полученные изображения; показать преподавателю.

== Продвинутая часть

> Стоимость — 3 балла

Веб-сервер — программа, которая принимает запросы по протоколу HTTP и возвращает клиенту (например, браузеру) запрашиваемые ресурсы. При этом он является одним из наиболее классических примеров сервисов в среде Linux. Подробнее о веб-серверах, HTTP-протоколе и сетевом взаимодействии Вы узнаете на курсе «Программирование сетевых приложений».

В данной части Вам необходимо:

1. Уставить веб-сервер nginx.
2. Запустить его сервис. Проверить в браузере работу сервера по адресу `localhost`.
3. Создать директорию для нового сайта. Для корректной работы её необходимо создавать в директории `/var/www`. Положить туда изображения графов, полученные в базовой части.
4. Сконфигурировать новый "сайт": отредактировать конфигурацию (обычно она живёт по пути `/etc/nginx/nginx.conf`), добавить туда новую директиву `server` с портом 4258 и `root`, указывающим на директорию для Вашего сайте. После изменения конфигурации перезапустите сервис nginx, чтобы изменения вступили в силу.
5. Проверить доступность "сайта". Скорее всего он будет доступен по адресу `localhost:4258/<имя файла>`

В качестве отчёта: сдать на HwProj список действий; показать преподавателю.
