= Что доступно в оболочке

== Как оболочка находит программы?

Когда вы вводите команду, оболочка ищет программу в каталогах, перечисленных в переменной окружения `$PATH`:

[,console]
----
missing:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
missing:~$ which echo
/bin/echo
----

`$PATH` -- двоеточия-разделённый список каталогов.
Оболочка ищет файл с именем команды в каждом каталоге по очереди.
Обойти `$PATH` можно, указав полный путь: `/bin/echo hello`.

Чтобы узнать, какие программы доступны:

[,console]
----
missing:~$ ls /bin
----

== Основные команды работы с файлами

`cat file`:: Выводит содержимое файла.
`sort file`:: Выводит строки файла в отсортированном порядке.
`uniq file`:: Удаляет последовательные дубликаты строк.
`head file` и `tail file`:: Выводят первые и последние строки файла соответственно.

== Поиск по содержимому: grep

`grep pattern file` -- находит строки, соответствующие шаблону в файле.
Шаблон -- это https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html[регулярное выражение].

[,console]
----
missing:~$ grep "error" log.txt
----

Можно указать каталог вместо файла и добавить `-r` для рекурсивного поиска:

[,console]
----
missing:~$ grep -r "TODO" ./src
----

== Текстовые редакторы командной строки

=== sed

`sed` -- программный редактор файлов.

[,console]
----
missing:~$ sed -i 's/pattern/replacement/g' file
----

Заменяет все вхождения `pattern` на `replacement` в файле `file`.
`-i` -- изменение файла на месте.
`s/` -- операция подстановки.
`/g` -- замена всех вхождений в строке.

=== awk

`awk` -- средство для анализа текстовых данных.
Наиболее частое применение -- извлечение колонок из файлов с регулярной структурой (CSV и т.д.):

[,console]
----
missing:~$ awk '{print $2}' file
----

Выводит вторую колонку (разделитель -- пробел) из каждой строки.
С `-F,` разделитель -- запятая.

== Пайпы (pipes)

Пайпы `|` позволяют соединять вывод одной программы со вводом другой:

[,console]
----
missing:~$ cat notes.txt | grep "important" | sort | uniq
----

Большинство программ работают со *стандартным вводом* (stdin), если не указан файл.
`|` берёт стандартный вывод (stdout) программы слева и передаёт его как стандартный ввод программы справа.

Это ключевая возможность оболочки -- *композиция* программ.

== Практический пример: анализ логов

[,console]
----
missing:~$ ssh myserver 'journalctl -u sshd -b-1 | grep "Disconnected from"' \
  | sed -E 's/.*Disconnected from .* user (.*) [^ ]+ port.*/\1/' \
  | sort | uniq -c \
  | sort -nk1,1 | tail -n10 \
  | awk '{print $2}' | paste -sd,
postgres,mysql,oracle,dell,ubuntu,inspur,test,admin,user,root
----

Эта команда:

. Подключается к удалённому серверу и извлекает логи SSH.
. Ищет сообщения об отключении.
. Извлекает имя пользователя из каждого сообщения.
. Подсчитывает частоту и выводит топ-10 пользователей через запятую.

Всё -- одной командой!
