= 1. Оболочка (Shell)

== Что такое оболочка?

У компьютеров существует множество интерфейсов для ввода команд: графические, голосовые, AR/VR и ИИ-ассистенты.
Они отлично работают в 80% случаев, но фундаментально ограничены в том, что позволяют делать -- невозможно нажать кнопку, которой нет, или отдать голосовую команду, которая не запрограммирована.
Чтобы получить полный контроль над инструментами компьютера, нужно опуститься до текстового интерфейса -- оболочки (shell).

Почти все платформы имеют оболочку в той или иной форме.
Несмотря на различия в деталях, все они примерно одинаковы: позволяют запускать программы, передавать им входные данные и просматривать вывод.

Для работы с оболочкой нужен *терминал* -- визуальный интерфейс.
Откройте его:

* *Linux:* `Ctrl + Alt + T` или найдите "Терминал" в меню приложений.
* *Windows:* `Win + R`, введите `cmd` или `powershell`. Или используйте https://docs.microsoft.com/en-us/windows/wsl/[WSL].
* *macOS:* `Cmd + Space`, введите "Terminal".

На Linux и macOS обычно открывается bash -- одна из наиболее распространённых оболочек.
Её синтаксис похож на многие другие оболочки.

Другие оболочки (fish, zsh) имеют удобства по сравнению с bash, но они менее универсальны и опираются на те же концепции.

== Зачем это нужно?

Оболочка не просто быстрее "кликанья мышкой" -- она обладает выразительностью, которой нет ни в одной графической программе.
Оболочка позволяет *комбинировать* программы творческими способами для автоматизации любых задач.

Знание оболочки полезно для:

* Работы с open-source софтом (инструкции по установке часто требуют оболочку).
* Построения CI/CD для проектов.
* Отладки ошибок при сбоях других программ.
